"use client";

import { useMutation } from "@tanstack/react-query";
import { Download, Upload } from "lucide-react";
import { useState } from "react";
import type { Schemas } from "@api/client";
import { TextArea, Toggle } from "@/components/console/form";
import { Badge, Button, Card, PageHeader } from "@/components/console/ui";
import { downloadWithToken } from "@/lib/console/ops";
import { useConsole } from "@/lib/console/session";
import { ErrorLine } from "./access/common";
import { CopyButton, RevealModal, type Revealed } from "./clients/reveal";

type Report = Schemas["ApplyReport"];
type Change = Schemas["Change"];

const OP_TONE: Record<Change["op"], "ok" | "accent" | "danger"> = { create: "ok", update: "accent", delete: "danger" };

/**
 * Tenant configuration as code: download the `ridm.tenant/1` document, or
 * paste one and preview the plan (creates, field-level updates, deletes with
 * prune) before applying it. Secrets of created clients and webhooks are
 * shown exactly once.
 */
export function ConfigPage({ tenant }: { tenant: string }) {
  const { client, can } = useConsole();
  const [text, setText] = useState("");
  const [prune, setPrune] = useState(false);
  const [plan, setPlan] = useState<Report | null>(null);
  const [revealed, setRevealed] = useState<Revealed | null>(null);

  const exp = useMutation({ mutationFn: () => downloadWithToken(`/admin/tenants/${encodeURIComponent(tenant)}/export`) });
  const load = useMutation({
    mutationFn: async () => {
      const { data, error } = await client.GET("/admin/tenants/{slug}/export", { params: { path: { slug: tenant } } });
      if (error) throw new Error(error.detail ?? error.title);
      return JSON.stringify(data, null, 2);
    },
    onSuccess: (doc) => {
      setText(doc);
      setPlan(null);
    },
  });
  const run = useMutation({
    mutationFn: async (dryRun: boolean) => {
      let body: unknown;
      try {
        body = JSON.parse(text);
      } catch {
        throw new Error("The document is not valid JSON.");
      }
      const { data, error } = await client.POST("/admin/tenants/{slug}/import", { params: { path: { slug: tenant }, query: { dry_run: dryRun, prune } }, body: body as never });
      if (error) throw new Error(error.errors?.map((e) => `${e.field}: ${e.message}`).join("; ") || error.detail || error.title);
      return data;
    },
    onSuccess: (r) => {
      setPlan(r);
      const secrets = [...Object.entries(r.secrets?.clients ?? {}).map(([k, v]) => ({ label: `Client secret · ${k}`, value: v })), ...Object.entries(r.secrets?.webhooks ?? {}).map(([k, v]) => ({ label: `Webhook secret · ${k}`, value: v }))];
      if (!r.dry_run && secrets.length) setRevealed({ title: "Secrets of created items", description: "Generated by this import; they are not part of the document.", values: secrets });
    },
  });
  const pick = async (file: File | undefined) => {
    if (!file) return;
    setText(await file.text());
    setPlan(null);
  };
  const grouped = new Map<string, Change[]>();
  for (const c of plan?.changes ?? []) grouped.set(c.resource, [...(grouped.get(c.resource) ?? []), c]);

  return (
    <>
      <PageHeader title="Export & import" sub="The tenant's configuration as one JSON document: clients, roles, groups, scopes, mappers, templates, webhooks, IP rules, profile schema and settings. Never secrets." />
      <div className="flex flex-col gap-4">
        <Card title="Export">
          <div className="flex flex-wrap items-center gap-2">
            <Button variant="primary" disabled={!can("ridm:tenants:export") || exp.isPending} onClick={() => exp.mutate()}>
              <Download className="size-4" aria-hidden />
              Download {tenant}.ridm.json
            </Button>
            <Button disabled={!can("ridm:tenants:export") || load.isPending} onClick={() => load.mutate()}>
              Load into the editor below
            </Button>
            <span className="text-[0.8125rem] text-muted">Deterministic: sorted collections, natural keys, no ids. Apply it to another tenant to copy its configuration.</span>
          </div>
          <ErrorLine error={exp.error ?? load.error} />
        </Card>
        <Card title="Import">
          <div className="flex flex-col gap-3">
            <div className="flex flex-wrap items-center gap-3">
              <label className="text-[0.875rem] text-ink">
                <span className="sr-only">Choose a document</span>
                <input type="file" accept=".json,application/json" onChange={(e) => void pick(e.target.files?.[0])} className="text-[0.8125rem] text-muted file:me-3 file:rounded-[var(--radius)] file:border file:border-line file:bg-paper file:px-3 file:py-1.5 file:text-[0.8125rem] file:text-ink" />
              </label>
              <Toggle label="Prune" hint="Also delete what the document does not mention (built-ins and standard scopes are never deleted)." checked={prune} onChange={(v) => { setPrune(v); setPlan(null); }} />
            </div>
            <TextArea aria-label="Configuration document" value={text} onChange={(e) => { setText(e.target.value); setPlan(null); }} placeholder='{"format": "ridm.tenant/1", "tenant": {"slug": "…", "display_name": "…"}, …}' className="min-h-56" spellCheck={false} />
            <div className="flex flex-wrap gap-2">
              <Button variant="primary" disabled={!text.trim() || run.isPending || !can("ridm:tenants:import")} onClick={() => run.mutate(true)}>
                Preview changes
              </Button>
              <Button variant={plan?.dry_run && plan.changes.length ? "primary" : "secondary"} disabled={!plan?.dry_run || plan.changes.length === 0 || run.isPending || !can("ridm:tenants:import")} onClick={() => run.mutate(false)}>
                <Upload className="size-4" aria-hidden />
                {run.isPending ? "Working…" : "Apply"}
              </Button>
              {text && <CopyButton value={text} label="Copy document" />}
            </div>
            <ErrorLine error={run.error} />
          </div>
        </Card>
        {plan && (
          <Card
            title={plan.dry_run ? "Planned changes" : "Applied"}
            actions={
              <span className="flex flex-wrap gap-1.5" role="status">
                <Badge tone="ok">{plan.summary.create} create</Badge>
                <Badge tone="accent">{plan.summary.update} update</Badge>
                <Badge tone="danger">{plan.summary.delete} delete</Badge>
                <Badge>{plan.summary.unchanged} unchanged</Badge>
                {!plan.dry_run && <Badge tone="ok">{plan.applied} applied</Badge>}
              </span>
            }
          >
            {plan.errors.length > 0 && (
              <ul className="mb-3 rounded-[var(--radius)] bg-danger-soft px-4 py-2 text-[0.8125rem] text-danger" role="alert">
                {plan.errors.map((e) => (
                  <li key={`${e.resource}/${e.key}`}>
                    {e.resource} {e.key}: {e.error}
                  </li>
                ))}
              </ul>
            )}
            {plan.changes.length === 0 ? (
              <p className="text-[0.875rem] text-muted">The document matches the tenant: nothing to do.</p>
            ) : (
              <div className="flex flex-col gap-4">
                {[...grouped.entries()].map(([resource, changes]) => (
                  <section key={resource} aria-label={resource}>
                    <h3 className="mb-1 text-[0.8125rem] font-semibold uppercase tracking-wide text-muted">{resource}</h3>
                    <ul className="divide-y divide-line rounded-[var(--radius)] border border-line">
                      {changes.map((c) => (
                        <li key={`${c.op}/${c.key}`} className="px-3 py-2 text-[0.875rem]">
                          <div className="flex items-center gap-2">
                            <Badge tone={OP_TONE[c.op]}>{c.op}</Badge>
                            <span className="font-mono text-[0.8125rem] text-ink">{c.key}</span>
                          </div>
                          {c.fields && c.fields.length > 0 && (
                            <dl className="mt-1.5 grid gap-1 sm:grid-cols-[minmax(8rem,auto)_minmax(0,1fr)]">
                              {c.fields.map((f) => (
                                <div key={f.field} className="contents">
                                  <dt className="font-mono text-[0.75rem] text-muted">{f.field}</dt>
                                  <dd className="flex min-w-0 flex-wrap gap-2 font-mono text-[0.75rem]">
                                    <Val value={f.from} tone="from" />
                                    <Val value={f.to} tone="to" />
                                  </dd>
                                </div>
                              ))}
                            </dl>
                          )}
                        </li>
                      ))}
                    </ul>
                  </section>
                ))}
              </div>
            )}
          </Card>
        )}
      </div>
      <RevealModal revealed={revealed} onClose={() => setRevealed(null)} />
    </>
  );
}

/** A diff value; long JSON collapses behind its first characters. */
function Val({ value, tone }: { value: unknown; tone: "from" | "to" }) {
  const text = JSON.stringify(value) ?? "null";
  const cls = tone === "from" ? "rounded bg-danger-soft px-1.5 text-danger line-through" : "rounded bg-ok-soft px-1.5 text-ok";
  if (text.length <= 80) return <span className={cls}>{text}</span>;
  return (
    <details className="min-w-0 max-w-full">
      <summary className={`cursor-pointer ${cls}`}>{text.slice(0, 80)}…</summary>
      <pre tabIndex={0} aria-label={tone === "from" ? "Previous value" : "New value"} className="mt-1 max-h-48 overflow-auto rounded-[var(--radius)] bg-ground px-2 py-1 text-ink">
        {JSON.stringify(value, null, 2)}
      </pre>
    </details>
  );
}
