-- 0005: per-tenant random salt for pairwise subject identifiers
-- (OIDC Core §8.1). Generated by the database so it exists for every tenant,
-- including ones created by earlier versions; never exported.
ALTER TABLE tenants
    ADD COLUMN pairwise_salt bytea NOT NULL DEFAULT gen_random_bytes(32);
