-- 0001: tenants (global table) and shared helpers.
--
-- Conventions used by every later migration:
--   * ids are UUIDs generated by the application (v7); the default is a fallback.
--   * every tenant-scoped table carries tenant_id and enables row level security
--     using current_tenant_id(), which the API sets per transaction with
--     SET LOCAL app.tenant_id = '<uuid>'.
--   * updated_at is maintained by the set_updated_at() trigger.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- Tenant currently bound to the transaction (NULL when unset, e.g. for global
-- admin operations that deliberately span tenants).
CREATE OR REPLACE FUNCTION current_tenant_id() RETURNS uuid
LANGUAGE sql STABLE AS $$
    SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid
$$;

CREATE TABLE tenants (
    id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    slug          text        NOT NULL,
    display_name  text        NOT NULL,
    status        text        NOT NULL DEFAULT 'active',
    settings      jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT tenants_slug_format CHECK (slug ~ '^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$'),
    CONSTRAINT tenants_status_check CHECK (status IN ('active', 'disabled')),
    CONSTRAINT tenants_slug_key UNIQUE (slug)
);

CREATE TRIGGER tenants_set_updated_at
    BEFORE UPDATE ON tenants
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- The master tenant hosts global administrators.
INSERT INTO tenants (id, slug, display_name)
VALUES ('00000000-0000-7000-8000-000000000001', 'master', 'Master')
ON CONFLICT (slug) DO NOTHING;
