mod apps;
mod contact;
mod data;
mod devices;
mod identities;
mod me;
mod mfa;
mod organizations;
mod password;
mod profile;
mod sessions;
mod tokens;

pub use apps::apps_router;
pub use contact::contact_router;
pub use data::data_router;
pub use devices::devices_router;
pub use identities::identities_router;
pub use me::me_router;
pub use mfa::mfa_router;
pub use organizations::organizations_router as account_organizations_router;
pub use password::password_router;
pub use profile::profile_router;
pub use sessions::sessions_router;
pub use tokens::tokens_router;
