{{- $inline := include "ridm.inlineSecrets" . | fromYaml }}
{{- if $inline }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ridm.fullname" . }}
  labels:
    {{- include "ridm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := $inline }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
  {{- end }}
{{- end }}
